name: Build

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

env:
  BuildConfig: Release
  SolutionFile: Blockcore.Vault.sln

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
      #- uses: aarnott/nbgv@v0.3 # https://github.com/AArnott/nbgv
      #  id: nbgv

      #- name: Versioning
      #  run: echo ${{ steps.nbgv.outputs.SemVer2 }}

      - name: Build with dotnet
        #run: dotnet build --configuration ${{ env.BuildConfig }} /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}
        run: dotnet build --configuration ${{ env.BuildConfig }}

      - name: Test with dotnet
        run: dotnet test ${{ env.SolutionFile }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install and npm run build
        working-directory: src/Blockcore.Vault.Admin/ClientApp
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/Blockcore.Vault.Admin/ClientApp/dist
          cname: vault.blockcore.net